# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lyq/Sources/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lyq/Sources/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lyq/Sources/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue/CMakeFiles /home/lyq/Sources/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lyq/Sources/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FreenectDriver

# Build rule for target.
FreenectDriver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FreenectDriver
.PHONY : FreenectDriver

# fast build rule for target.
FreenectDriver/fast:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/build
.PHONY : FreenectDriver/fast

#=============================================================================
# Target rules for targets named Salient_Region_Detection_With_Convex_Hull_Overlap_Cue

# Build rule for target.
Salient_Region_Detection_With_Convex_Hull_Overlap_Cue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Salient_Region_Detection_With_Convex_Hull_Overlap_Cue
.PHONY : Salient_Region_Detection_With_Convex_Hull_Overlap_Cue

# fast build rule for target.
Salient_Region_Detection_With_Convex_Hull_Overlap_Cue/fast:
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build
.PHONY : Salient_Region_Detection_With_Convex_Hull_Overlap_Cue/fast

comman.o: comman.cpp.o
.PHONY : comman.o

# target to build an object file
comman.cpp.o:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/comman.cpp.o
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/comman.cpp.o
.PHONY : comman.cpp.o

comman.i: comman.cpp.i
.PHONY : comman.i

# target to preprocess a source file
comman.cpp.i:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/comman.cpp.i
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/comman.cpp.i
.PHONY : comman.cpp.i

comman.s: comman.cpp.s
.PHONY : comman.s

# target to generate assembly for a file
comman.cpp.s:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/comman.cpp.s
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/comman.cpp.s
.PHONY : comman.cpp.s

cutobj.o: cutobj.cpp.o
.PHONY : cutobj.o

# target to build an object file
cutobj.cpp.o:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/cutobj.cpp.o
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/cutobj.cpp.o
.PHONY : cutobj.cpp.o

cutobj.i: cutobj.cpp.i
.PHONY : cutobj.i

# target to preprocess a source file
cutobj.cpp.i:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/cutobj.cpp.i
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/cutobj.cpp.i
.PHONY : cutobj.cpp.i

cutobj.s: cutobj.cpp.s
.PHONY : cutobj.s

# target to generate assembly for a file
cutobj.cpp.s:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/cutobj.cpp.s
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/cutobj.cpp.s
.PHONY : cutobj.cpp.s

evaluate.o: evaluate.cpp.o
.PHONY : evaluate.o

# target to build an object file
evaluate.cpp.o:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/evaluate.cpp.o
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/evaluate.cpp.o
.PHONY : evaluate.cpp.o

evaluate.i: evaluate.cpp.i
.PHONY : evaluate.i

# target to preprocess a source file
evaluate.cpp.i:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/evaluate.cpp.i
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/evaluate.cpp.i
.PHONY : evaluate.cpp.i

evaluate.s: evaluate.cpp.s
.PHONY : evaluate.s

# target to generate assembly for a file
evaluate.cpp.s:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/evaluate.cpp.s
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/evaluate.cpp.s
.PHONY : evaluate.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/main.cpp.s
.PHONY : main.cpp.s

ncut.o: ncut.cpp.o
.PHONY : ncut.o

# target to build an object file
ncut.cpp.o:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/ncut.cpp.o
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/ncut.cpp.o
.PHONY : ncut.cpp.o

ncut.i: ncut.cpp.i
.PHONY : ncut.i

# target to preprocess a source file
ncut.cpp.i:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/ncut.cpp.i
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/ncut.cpp.i
.PHONY : ncut.cpp.i

ncut.s: ncut.cpp.s
.PHONY : ncut.s

# target to generate assembly for a file
ncut.cpp.s:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/ncut.cpp.s
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/ncut.cpp.s
.PHONY : ncut.cpp.s

pyramid.o: pyramid.cpp.o
.PHONY : pyramid.o

# target to build an object file
pyramid.cpp.o:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/pyramid.cpp.o
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/pyramid.cpp.o
.PHONY : pyramid.cpp.o

pyramid.i: pyramid.cpp.i
.PHONY : pyramid.i

# target to preprocess a source file
pyramid.cpp.i:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/pyramid.cpp.i
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/pyramid.cpp.i
.PHONY : pyramid.cpp.i

pyramid.s: pyramid.cpp.s
.PHONY : pyramid.s

# target to generate assembly for a file
pyramid.cpp.s:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/pyramid.cpp.s
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/pyramid.cpp.s
.PHONY : pyramid.cpp.s

saliency.o: saliency.cpp.o
.PHONY : saliency.o

# target to build an object file
saliency.cpp.o:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/saliency.cpp.o
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/saliency.cpp.o
.PHONY : saliency.cpp.o

saliency.i: saliency.cpp.i
.PHONY : saliency.i

# target to preprocess a source file
saliency.cpp.i:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/saliency.cpp.i
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/saliency.cpp.i
.PHONY : saliency.cpp.i

saliency.s: saliency.cpp.s
.PHONY : saliency.s

# target to generate assembly for a file
saliency.cpp.s:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/saliency.cpp.s
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/saliency.cpp.s
.PHONY : saliency.cpp.s

segment.o: segment.cpp.o
.PHONY : segment.o

# target to build an object file
segment.cpp.o:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/segment.cpp.o
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/segment.cpp.o
.PHONY : segment.cpp.o

segment.i: segment.cpp.i
.PHONY : segment.i

# target to preprocess a source file
segment.cpp.i:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/segment.cpp.i
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/segment.cpp.i
.PHONY : segment.cpp.i

segment.s: segment.cpp.s
.PHONY : segment.s

# target to generate assembly for a file
segment.cpp.s:
	$(MAKE) -f CMakeFiles/FreenectDriver.dir/build.make CMakeFiles/FreenectDriver.dir/segment.cpp.s
	$(MAKE) -f CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/build.make CMakeFiles/Salient_Region_Detection_With_Convex_Hull_Overlap_Cue.dir/segment.cpp.s
.PHONY : segment.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... FreenectDriver"
	@echo "... Salient_Region_Detection_With_Convex_Hull_Overlap_Cue"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... comman.o"
	@echo "... comman.i"
	@echo "... comman.s"
	@echo "... cutobj.o"
	@echo "... cutobj.i"
	@echo "... cutobj.s"
	@echo "... evaluate.o"
	@echo "... evaluate.i"
	@echo "... evaluate.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... ncut.o"
	@echo "... ncut.i"
	@echo "... ncut.s"
	@echo "... pyramid.o"
	@echo "... pyramid.i"
	@echo "... pyramid.s"
	@echo "... saliency.o"
	@echo "... saliency.i"
	@echo "... saliency.s"
	@echo "... segment.o"
	@echo "... segment.i"
	@echo "... segment.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

